# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Administrator/Desktop/DD_Proj/project_1/rtl_1.xdc

# IP: ip/image_0/image_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_0 || ORIG_REF_NAME==image_0} -quiet] -quiet
